-- ============================================================================
-- Migration: add Connection.blocked_by_id  (audit finding C-3)
-- ============================================================================
--
-- IMPORTANT: this is a plain SQL script, NOT an Alembic revision file.
-- No migrations/ directory was supplied as part of this implementation
-- pass, so I can't safely generate a real Alembic revision without knowing
-- your current migration head/chain (getting that wrong would corrupt your
-- migration history). Please turn this into a proper revision yourself,
-- e.g.:
--
--     flask db migrate -m "add blocked_by_id to connections"
--     # then verify the autogenerated upgrade()/downgrade() match the SQL
--     # below before running `flask db upgrade`
--
-- What this changes and why
-- --------------------------
-- Connection.block_user() used to record "who blocked whom" by swapping
-- requester_id/receiver_id on the existing row so that receiver_id always
-- meant "the blocker" — which corrupted the original connection-request's
-- history and disagreed with at least two other, independently-written
-- "is this blocked" checks elsewhere in the codebase (see audit finding
-- C-3 for the full writeup). blocked_by_id is a new, explicit,
-- unambiguous column that fixes this: requester_id/receiver_id are never
-- mutated to express blocking anymore.
--
-- This migration is purely additive (a new nullable column) — it does not
-- change or delete any existing data, and existing rows are unaffected
-- until a future block/unblock action touches them.
-- ============================================================================

ALTER TABLE connections
    ADD COLUMN blocked_by_id INTEGER NULL REFERENCES users(id);

CREATE INDEX IF NOT EXISTS ix_connections_blocked_by_id
    ON connections (blocked_by_id);

-- ----------------------------------------------------------------------------
-- Optional backfill (recommended, not required)
-- ----------------------------------------------------------------------------
-- Existing rows with status = 'blocked' predate blocked_by_id and have no
-- way to recover "who actually clicked block" — that information was lost
-- the moment the old code swapped requester_id/receiver_id. The best you
-- can safely infer for pre-existing rows is "the current receiver_id was
-- probably the blocker," which is only true for connections that were
-- blocked under the OLD code path (connections.py::block_user) and were
-- never touched by the messaging blueprint's differently-broken block path
-- (messages.py::block_user_messaging) — there is no way to distinguish
-- these cases after the fact. Given that ambiguity, an automatic backfill
-- is deliberately NOT included here; decide case-by-case (or simply leave
-- blocked_by_id NULL for pre-existing blocked rows and let each affected
-- user re-block if the direction turns out to matter to them) rather than
-- risk recording a confidently-wrong "who blocked whom" for historical data.
--
-- If you do want a best-effort backfill, this is the assumption it would
-- encode — review it before running:
--
-- UPDATE connections
--    SET blocked_by_id = receiver_id
--  WHERE status = 'blocked'
--    AND blocked_by_id IS NULL;

-- ----------------------------------------------------------------------------
-- Downgrade
-- ----------------------------------------------------------------------------
-- DROP INDEX IF EXISTS ix_connections_blocked_by_id;
-- ALTER TABLE connections DROP COLUMN blocked_by_id;
