"""
services/upload_validation_service.py

Document 3 §3: hardens file-upload validation across every upload
endpoint (messages.py::upload_message_resource, posts.py::upload_post_resource,
learnora.py::upload_post_attachment, threads.py::upload_thread_attachment,
profile.py::upload_avatar, threads.py::upload_thread_avatar).

validate_and_normalize_image(): opens the upload with Pillow, verifies
it's a genuine raster image, re-encodes it (stripping any embedded
scripting/metadata in the process), and returns a clean BytesIO. This is
what makes SVG-as-.jpg (or any other extension-spoofed non-image)
rejected by construction rather than by extension-sniffing, which the
existing ALLOWED_IMAGE_EXT check alone cannot prevent.

validate_document_mime(): for non-image uploads, checks the real
magic-number signature against a small hand-rolled table rather than
trusting the filename extension. Uses the hand-rolled table (not
python-magic) per your standing instruction to avoid new dependencies
unless explicitly approved — python-magic needs a native libmagic
dependency in the deployment environment, which Document 3 §3 flagged as
needing separate approval; this ships without it.

Per Document 2 §2's layering rule: no Flask imports, no request/session/g.
"""

from __future__ import annotations

from io import BytesIO

from PIL import Image, UnidentifiedImageError

from errors import ValidationError

# ============================================================================
# IMAGE VALIDATION
# ============================================================================

# Formats we intentionally accept when re-encoding. Deliberately excludes
# animated formats' extra frames (re-encoding a GIF via Pillow's default
# save collapses to the first frame) — callers that need to preserve GIF
# animation should special-case that format rather than calling this
# generic normalizer.
_SAFE_OUTPUT_FORMAT = {
    "JPEG": "JPEG",
    "PNG": "PNG",
    "GIF": "GIF",
    "WEBP": "WEBP",
}


def validate_and_normalize_image(file_storage) -> BytesIO:
    """
    Validate that `file_storage` is a genuine raster image and return a
    clean, re-encoded BytesIO ready to hand to Cloudinary (or any other
    upload backend).

    Steps (per Document 3 §3):
      1. Image.open(...).verify() — cheap structural check, but leaves
         the file object in a state where it can't be used again, so a
         second Image.open() is required for step 2.
      2. Re-open + .load() — actually decodes pixel data, catching
         truncated/corrupt files that .verify() alone can miss.
      3. Re-encode to a fresh BytesIO in the same format — this is what
         strips any embedded scripts/metadata/polyglot payloads, since
         the output bytes are freshly generated by Pillow from decoded
         pixel data, not a copy of the original file bytes.

    Raises ValidationError for anything that isn't a genuine, decodable
    raster image in an allowed format.
    """
    if file_storage is None:
        raise ValidationError("No file provided")

    try:
        file_storage.stream.seek(0)
    except (AttributeError, OSError):
        pass

    raw = file_storage.read()
    if not raw:
        raise ValidationError("File is empty")

    # Step 1: structural verify (consumes the file object)
    try:
        probe = Image.open(BytesIO(raw))
        probe.verify()
    except (UnidentifiedImageError, OSError, ValueError):
        raise ValidationError("File is not a valid image")

    # Step 2: re-open + fully decode (verify() alone can miss truncation)
    try:
        img = Image.open(BytesIO(raw))
        img.load()
    except (UnidentifiedImageError, OSError, ValueError):
        raise ValidationError("Image file is corrupt or truncated")

    fmt = (img.format or "").upper()
    if fmt not in _SAFE_OUTPUT_FORMAT:
        raise ValidationError(
            f"Unsupported image format: {fmt or 'unknown'}. "
            f"Allowed: {', '.join(_SAFE_OUTPUT_FORMAT)}"
        )

    # Step 3: re-encode from decoded pixel data into a fresh buffer.
    # JPEG doesn't support an alpha channel — flatten to RGB first so
    # re-encoding a PNG-with-transparency uploaded as .jpg doesn't crash.
    output_format = _SAFE_OUTPUT_FORMAT[fmt]
    if output_format == "JPEG" and img.mode in ("RGBA", "LA", "P"):
        img = img.convert("RGB")

    clean = BytesIO()
    save_kwargs = {}
    if output_format == "JPEG":
        save_kwargs["quality"] = 90
    img.save(clean, format=output_format, **save_kwargs)
    clean.seek(0)

    return clean


# ============================================================================
# DOCUMENT MIME-TYPE VALIDATION (magic-number based, no python-magic)
# ============================================================================

# Signature bytes for the handful of non-image document types this app
# accepts. Checked against the first N bytes of the file — this is what
# makes filename-extension spoofing structurally harder without adding
# the python-magic/libmagic dependency (deferred pending approval per
# Document 3 §3).
_MAGIC_SIGNATURES = {
    "application/pdf": [(0, b"%PDF-")],
    # DOCX/XLSX/PPTX are ZIP containers — all share the ZIP local-file-header
    # magic number. We can't distinguish between them from the signature
    # alone (that requires inspecting the ZIP's internal file listing),
    # so callers pass the specific mime they expect and we just confirm
    # "this is at least a genuine ZIP", which rules out non-ZIP files
    # wearing a .docx/.xlsx extension.
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [(0, b"PK\x03\x04")],
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [(0, b"PK\x03\x04")],
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": [(0, b"PK\x03\x04")],
    # Legacy .doc/.ppt/.xls (OLE Compound File Binary Format) share this signature.
    "application/msword": [(0, b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1")],
    "text/plain": [],  # no reliable signature — allowed through unchecked
    "text/csv": [],     # same
}


def validate_document_mime(file_storage, allowed_mimes: set[str]) -> None:
    """
    Read the first bytes of `file_storage` and check the real magic-number
    signature against `allowed_mimes`, rather than trusting the filename
    extension alone. Raises ValidationError if the file's actual content
    doesn't match any of the allowed signatures.

    Mime types with no reliable magic-number signature (plain text, CSV)
    pass through unchecked — there's nothing structural to verify for
    those, so extension-based trust is the practical ceiling there and
    this function doesn't pretend otherwise.

    Does not consume/rewind assumptions beyond what's needed: seeks back
    to position 0 after reading, so the caller can still read the full
    file afterward for the actual upload.
    """
    if file_storage is None:
        raise ValidationError("No file provided")

    try:
        file_storage.stream.seek(0)
    except (AttributeError, OSError):
        pass

    header = file_storage.read(16)

    try:
        file_storage.stream.seek(0)
    except (AttributeError, OSError):
        pass

    if not header:
        raise ValidationError("File is empty")

    checkable_mimes = [m for m in allowed_mimes if _MAGIC_SIGNATURES.get(m)]

    if not checkable_mimes:
        # None of the allowed mimes have a signature we can verify
        # (e.g. only text/plain was allowed) — nothing more to check.
        return

    for mime in checkable_mimes:
        for offset, signature in _MAGIC_SIGNATURES[mime]:
            if header[offset:offset + len(signature)] == signature:
                return

    raise ValidationError(
        "File content does not match its expected type — "
        "the file may be corrupted or mislabeled"
    )
